/**
 * Events.js — all Socket.IO event name constants.
 * No magic strings inline anywhere in the codebase.
 */
export const Events = {
    // Client → Server
    JOIN_ROOM: 'JOIN_ROOM',
    PLAYER_INPUT: 'PLAYER_INPUT',
    ARSENAL_EQUIP: 'ARSENAL_EQUIP',
    RESUPPLY_REQ: 'RESUPPLY_REQ',
    LEAVE_ROOM: 'LEAVE_ROOM',

    // Server → Client
    ROOM_JOINED: 'ROOM_JOINED',
    ROOM_FULL: 'ROOM_FULL',
    WORLD_SNAPSHOT: 'WORLD_SNAPSHOT',
    SPAWN: 'SPAWN',
    HIT: 'HIT',
    KILL: 'KILL',
    POINT_CAPTURED: 'POINT_CAPTURED',
    ROUTE_ADVANCED: 'ROUTE_ADVANCED',
    FINAL_STAND_START: 'FINAL_STAND_START',
    FINAL_STAND_ENDED: 'FINAL_STAND_ENDED',
    MATCH_END: 'MATCH_END',
    RESUPPLY_GRANTED: 'RESUPPLY_GRANTED',
    RECONCILE: 'RECONCILE',
    EQUIP_CONFIRMED: 'EQUIP_CONFIRMED',
    PLAYER_JOINED: 'PLAYER_JOINED',
    PLAYER_LEFT: 'PLAYER_LEFT',
};
